/**
 * Renders a Velite-compiled MDX function-body string as a React component.
 *
 * SECURITY: `code` is a `CompiledMdxCode` — a nominal brand that can only be
 * produced by `asCompiledMdxCode()` (src/lib/mdx/compiled-mdx.ts), which
 * validates the artifact loaded from Velite's build output. That output is the
 * compiled form of the MDX files committed to this repository
 * (`src/content/blog/*.mdx`), never request input:
 *
 *   - `code` is generated by Velite's MDX compiler at build time
 *   - MDX source files are authored content committed to git
 *   - Only trusted developers can modify .mdx files
 *   - The component is server-only (see import below)
 *
 * Evaluating a function body is inherent to how MDX compilers emit output, so
 * this is the one place in the codebase where `new Function` is allowed. The
 * project's ESLint config enables `no-new-func` to keep it that way — the
 * directive below is the single, intentional exception.
 *
 * `import "server-only"` prevents this module from being included in any
 * client bundle. If this import is removed, Next.js will silently bundle
 * `new Function()` into client-side code — a security regression.
 *
 * Do NOT add `"use client"` to this file.
 *
 * See docs/security.md → "Content Trust Boundaries" (compiled MDX).
 */
import "server-only";
import * as runtime from "react/jsx-runtime";
import type { CompiledMdxCode } from "@/lib/mdx/compiled-mdx";

interface MdxContentProps {
  readonly code: CompiledMdxCode;
}

/** Runtime functions injected into every compiled MDX module. */
const MDX_RUNTIME = Object.freeze({ ...runtime });

export default function MdxContent({ code }: MdxContentProps) {
  let Component: React.ComponentType;

  try {
    // eslint-disable-next-line no-new-func, @typescript-eslint/no-implied-eval -- Velite emits a function body; this is the only sanctioned evaluation point, and `code` is a validated build artifact (see src/lib/mdx/compiled-mdx.ts).
    const evaluate = new Function(code);
    const evaluated: unknown = evaluate(MDX_RUNTIME);

    if (
      typeof evaluated !== "object" ||
      evaluated === null ||
      typeof (evaluated as { default?: unknown }).default !== "function"
    ) {
      throw new Error("Compiled MDX did not export a default component.");
    }

    Component = (evaluated as { default: React.ComponentType }).default;
  } catch (error) {
    // Fail loudly with context instead of surfacing an opaque render error:
    // a malformed artifact means the content pipeline is broken. `{ cause }`
    // preserves the original stack trace for diagnosis.
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to evaluate compiled MDX: ${message}`, { cause: error });
  }

  return <Component />;
}
