/**
 * Renders a Velite-compiled MDX function-body string as a React component.
 *
 * SECURITY: This module uses `new Function()` to evaluate Velite-compiled MDX
 * code. The `code` parameter originates from the build-time Velite compilation
 * of local .mdx files (src/content/blog/*.mdx) — NOT from user input.
 *
 * Trust boundary:
 *   - `code` is generated by Velite's MDX compiler at build time
 *   - MDX source files are authored content committed to git
 *   - Only trusted developers can modify .mdx files
 *   - The component is server-only (see import below)
 *
 * `import "server-only"` prevents this module from being included in any
 * client bundle. If this import is removed, Next.js will silently bundle
 * `new Function()` into client-side code — a security regression.
 *
 * Do NOT add `"use client"` to this file.
 */
import "server-only";
import * as runtime from "react/jsx-runtime";

interface MdxContentProps {
  readonly code: string;
}
export default function MdxContent({ code }: MdxContentProps) {
  const fn = new Function(code);
  const Component = fn({ ...runtime }).default as React.ComponentType<{
    components?: Record<string, React.ComponentType>;
  }>;

  return <Component />;
}
