import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { asCompiledMdxCode } from "@/lib/mdx/compiled-mdx";

/**
 * Security regression tests for the compiled-MDX trust boundary.
 *
 * The evaluator in src/components/blog/MdxContent.tsx only accepts
 * `CompiledMdxCode`, which `asCompiledMdxCode()` is the sole producer of. These
 * tests pin the runtime marker check: strings without the expected MDX
 * function-body marker are never branded, so a corrupted or substituted build
 * artifact fails closed instead of being evaluated. (The check rejects strings
 * lacking that marker — it is not a general JavaScript integrity check, and
 * JavaScript that merely happens to contain the marker is still branded. The
 * brand itself is enforced by `npm run typecheck`.)
 *
 * The unit tests below run against SYNTHETIC_FUNCTION_BODY — a hand-written
 * stand-in with the shape Velite's MDX compiler emits, so it pins the
 * validator's behaviour, not the compiler's output. The contract with the real
 * compiler is pinned separately by "compiled MDX generated by Velite" at the
 * bottom of this file, which validates Velite's own build artifact. That suite
 * is what catches an output-format change (e.g. a Velite/MDX upgrade) before a
 * post is published: the render gate in src/lib/velite/index.ts only runs for
 * published posts, so it cannot catch it.
 */

/**
 * Hand-written function body with the shape Velite's MDX compiler emits.
 * Deliberately synthetic — see the generated-output suite at the bottom.
 */
const SYNTHETIC_FUNCTION_BODY =
  'const{Fragment:e,jsx:n,jsxs:t}=arguments[0];function _createMdxContent(i){return n("p",{children:"hi"})}';

describe("asCompiledMdxCode", () => {
  it("brands a compiled MDX function body", () => {
    const code = asCompiledMdxCode(SYNTHETIC_FUNCTION_BODY);
    expect(code).toBe(SYNTHETIC_FUNCTION_BODY);
  });

  it("trims surrounding whitespace", () => {
    expect(asCompiledMdxCode(`\n  ${SYNTHETIC_FUNCTION_BODY}\n`)).toBe(SYNTHETIC_FUNCTION_BODY);
  });

  it("rejects non-string values", () => {
    for (const value of [null, undefined, 42, true, {}, [], SYNTHETIC_FUNCTION_BODY.length]) {
      expect(asCompiledMdxCode(value)).toBeNull();
    }
  });

  it("rejects empty and whitespace-only strings", () => {
    expect(asCompiledMdxCode("")).toBeNull();
    expect(asCompiledMdxCode("   \n\t ")).toBeNull();
  });

  it("rejects JavaScript that is not compiled MDX output", () => {
    // Rejected because it lacks the MDX function-body marker, not because the
    // check is a sandbox — see the module docs.
    expect(asCompiledMdxCode("globalThis.__pwned = true;")).toBeNull();
    expect(asCompiledMdxCode("export default function () { return null; }")).toBeNull();
    expect(asCompiledMdxCode("require('node:child_process').execSync('id');")).toBeNull();
  });

  it("rejects oversized artifacts", () => {
    // ASCII: 5 MiB of characters is also 5 MiB of UTF-8 bytes, and the
    // marker-bearing prefix pushes it over the limit.
    const oversized = `${SYNTHETIC_FUNCTION_BODY}${"a".repeat(5 * 1024 * 1024)}`;
    expect(asCompiledMdxCode(oversized)).toBeNull();
  });

  it("rejects artifacts over the byte limit even when the character count is under it", () => {
    // The limit is measured in UTF-8 bytes while `code.length` counts UTF-16
    // code units: a marker-bearing artifact heavy in multibyte characters can
    // exceed 5 MiB of bytes while staying below 5,242,880 characters.
    const multibyte = `${SYNTHETIC_FUNCTION_BODY}${"é".repeat(3 * 1024 * 1024)}`;
    // 3,145,728 characters (< 5 MiB) but 6,291,456+ bytes (> 5 MiB).
    expect(multibyte.length).toBeLessThan(5 * 1024 * 1024);
    expect(asCompiledMdxCode(multibyte)).toBeNull();
  });

  it("brands multibyte artifacts under the byte limit", () => {
    // 1 MiB of characters, 2 MiB of UTF-8 bytes — comfortably under the limit,
    // so multibyte content is not wrongly rejected.
    const code = asCompiledMdxCode(`${SYNTHETIC_FUNCTION_BODY}${"é".repeat(1024 * 1024)}`);
    expect(code).not.toBeNull();
  });
});

// ── Contract with Velite's real output ────────────────────────────────────────

/** Velite's build artifact (written by `velite build`, which the gate workflow runs). */
const VELITE_POSTS_PATH = join(process.cwd(), ".velite", "posts.json");

/** The subset of a Velite post this suite reads. */
interface GeneratedPost {
  readonly slug: string;
  readonly published: boolean;
  readonly body: string;
}

/**
 * The posts Velite actually compiled. The gate workflow and `npm run typecheck`
 * build Velite before tests run; a bare `npm test` on a clean checkout builds
 * the artifact here instead of skipping, so this suite can never pass vacuously
 * against an empty or missing file.
 */
async function loadGeneratedPosts(): Promise<GeneratedPost[]> {
  const { build } = await import("velite");
  await build({ logLevel: "silent" });
  return JSON.parse(readFileSync(VELITE_POSTS_PATH, "utf-8")) as GeneratedPost[];
}

describe("compiled MDX generated by Velite", () => {
  let posts: GeneratedPost[] = [];

  beforeAll(async () => {
    posts = await loadGeneratedPosts();
  }, 60_000);

  it("compiles at least one post to validate", () => {
    // The assertions below must run against real compiler output.
    expect(posts.length).toBeGreaterThan(0);
  });

  it("keeps the function-body marker the validator requires", () => {
    // Pins the contract with Velite/MDX: if upstream changes its output shape,
    // this fails here rather than at render time for a published post.
    for (const post of posts) {
      expect(post.body, `${post.slug} lacks the MDX function-body marker`).toContain(
        "arguments[0]",
      );
    }
  });

  it("brands every generated post body, published or not", () => {
    // The render gate (src/lib/velite/index.ts) only brands published posts;
    // validating the whole artifact also covers still-unpublished posts.
    for (const post of posts) {
      expect(asCompiledMdxCode(post.body), `${post.slug} is not brandable`).not.toBeNull();
    }
  });
});
